all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3

  children:
    webservers:
      hosts:
        web-server-a:
          ansible_host: 192.168.0.50
        web-server-n:
          ansible_host: 192.168.0.51

    web_servers_apache:
      hosts:
        web-server-a:

    web_servers_nginx:
      hosts:
        web-server-n:
